apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-deployment
  labels:
    app: e-commerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-commerce
  template:
    metadata:
      labels:
        app: e-commerce
    spec:
      containers:
        - name: e-commerce
          image: vamshidhar1128/e-commerce:latest
          ports:
            - containerPort: 8081
